# Generated by Django 4.1.4 on 2022-12-11 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recharge_app', '0002_recharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='Recharge_app.plans'),
        ),
    ]
